---@class QuestieOptionsDefaults
local QuestieOptionsDefaults = QuestieLoader:CreateModule("QuestieOptionsDefaults");

---@type QuestieLib
local QuestieLib = QuestieLoader:ImportModule("QuestieLib")

function QuestieOptionsDefaults:Load()
    local iconPath = QuestieLib.AddonPath .. "Icons\\"

    return {
        profile = {
            clusterLevelHotzone = 1,
            enableIconLimit = false,
            iconLimit = 200,
            availableScale = 1,
            eventScale = 1,
            lootScale = 0.64,
            iconFadeLevel = 0.3,
            trackerLocked = true,
            monsterScale = 1,
            objectScale = 0.64,
            globalScale = 1,
            globalMiniMapScale = 1,
            fadeLevel = 20,
            fadeOverPlayer = true,
            fadeOverPlayerLevel = 0.5,
            fadeOverPlayerDistance = 5,
            nameplateX = 5,
            nameplateY = 0,
            nameplateScale = 2,
            nameplateEnabled = true,
            minimapCoordinatesEnabled = false,
            mapCoordinatesEnabled = false,
            mapCoordinatePrecision = 1,
            dbmHUDEnable = false,
            dbmHUDShowAlert = true,
            DBMHUDRefresh = 0.03,
            DBMHUDZoom = 100,
            dbmHUDRadius = 3,
            dbmHUDShowQuest = true,
            dbmHUDShowSlay = false,
            dbmHUDShowLoot = false,
            dbmHUDShowInteract = true,
            mapShowHideEnabled = true,
            nameplateTargetFrameEnabled = true,
            nameplateTargetFrameX = -30,
            nameplateTargetFrameY = 25,
            nameplateTargetFrameScale = 1.7,
            alwaysGlowMap = false,
            alwaysGlowMinimap = false,
            questObjectiveColors = true,
            questMinimapObjectiveColors = true,
            enableObjectives = true,
            enableTurnins = true,
            enableAvailable = true,
            enableTooltips = true,
            enableTooltipsItemID = false,
            enableTooltipsNPCID = true,
            enableTooltipsObjectID = false,
            enableTooltipsQuestID = false,
            enableTooltipsQuestLevel = true,
            showQuestXpAtMaxLevel = true,
            enableTooltipsNextInChain = true,
            enableMapIcons = true,
            enableMiniMapIcons = true,
            questieShutUp = false,
            bugWorkarounds = true,
            hideIconsOnContinents = true,

            -- Route lines (pfQuest-style)
            enableRoutes = true,
            enableRouteCluster = true,
            enableRouteEnder = true,
            enableRouteStarter = false,
            enableRouteArrow = true,
            routeArrowPosX = 475.6531254233598,
            routeArrowPosY = 276.888898706257,

            -- Tracker Settings Tab
            autoTrackQuests = true,
            trackerShowCompleteQuests = true,
            trackerShowQuestLevel = true,
            collapseCompletedQuests = false,
            collapseCompletedQuestsCurrentZoneOnly = false,
            trackerMirrorLFGObjectives = true,
            trackerLFGObjectivePosition = 0,
            trackerCollapseDirection = "normal",
            hideCompletedQuestObjectives = false,
            hideBlizzardCompletionText = false,
            hideCompletedAchieveObjectives = true,
            showBlizzardQuestTimer = true,
            trackerHeaderEnabled = true,
            moveHeaderToBottom = false,
            stickyDurabilityFrame = false,
            hideTrackerInCombat = false,
            hideTrackerInDungeons = false,
            trackerFadeMinMaxButtons = true,
            trackerFadeQuestItemButtons = false,
            trackerBackdropEnabled = true,
            currentBackdropEnabled = true,
            trackerBorderEnabled = false,
            currentBorderEnabled = false,
            trackerBackdropFader = true,
            currentBackdropFader = true,
            sizerHidden = false,
            listAchievementsFirst = true,
            stickyVoiceOverFrame = false,
            alwaysShowTracker = false,
            trackerColorObjectives = 'minimal',
            trackerSortObjectives = 'byZonePlayerProximity',
            trackerLayoutDensity = "balanced",
            trackerQuestItemButtonPosition = 'outsideLeft',
            trackerQuestItemGutter = 4,
            trackerQuestTitleInset = 0,
            trackerObjectiveInset = 0,
            trackerZoneSpacing = 0,
            trackerTopSpacing = 0,
            trackerBottomSpacing = 0,
            trackerHeaderDividerEnabled = true,
            trackerZoneDividersEnabled = false,
            trackerBackdropColor = { 0.0, 0.0, 0.0 },
            trackerBorderColor = { 1.0, 1.0, 1.0 },
            trackerHeaderBackgroundColor = { 0.0, 0.0, 0.0, 0.5 },
            trackerHeaderTextColor = { 1.0, 0.82, 0.0 },
            trackerHeaderAccentColor = { 0.16, 0.78, 0.72, 0.38 },
            trackerZoneDividerColor = { 0.16, 0.78, 0.72, 0.28 },
            trackerZoneHeaderColor = { 1.0, 0.0, 1.0 },
            trackerAlternatingRowsEnabled = false,
            trackerAlternatingRowColorOdd = { 0.018, 0.022, 0.031, 0.32 },
            trackerAlternatingRowColorEven = { 0.082, 0.855, 0.804, 0.08 },
            trackerAlternatingRowPaletteVersion = 0,
            trackerbindSetTomTom = 'ctrlleft',
            trackerbindOpenQuestLog = 'left',
            trackerbindUntrack = "shiftleft",
            trackerSetpoint = "TOPLEFT",
            trackerFontSizeHeader = 12,
            trackerFontGlobalOverride = "NONE",
            trackerFontGlobalScale = 1,
            trackerFontHeader = 'SourceCodePro (Bold)',
            trackerFontSizeZone = 12,
            trackerFontZone = 'SourceCodePro (Bold)',
            trackerFontSizeQuest = 12,
            trackerFontQuest = 'SourceCodePro (Bold)',
            trackerFontSizeObjective = 12,
            trackerFontObjective = 'SourceCodePro (Bold)',
            trackerQuestPadding = 2,
            trackerQuestTitlePadding = 1,
            trackerFontOutline = "OUTLINE",
            trackerBorderAlpha = 0.65,
            trackerBackdropAlpha = 0.65,
            trackerHeightRatio = 0.50,
            trackerScale = 1.00,

            lowLevelStyle = 2,
            manualLevelOffset = 7,
            minLevelFilter = 1,
            maxLevelFilter = 10,
            enabled = true,
            searchType = 1,
            autoaccept = false,
            autocomplete = false,
            autobuyQuestItems = false,
            autoModifier = "alt",
            acceptTrivial = false,
            questAnnounceChannel = "party",
            questAnnounceItems = true,
            questAnnounceAccepted = true,
            questAnnounceAbandoned = true,
            questAnnounceObjectives = true,
            questAnnounceCompleted = true,
            questAnnounceLocally = false,
            hideUnexploredMapIcons = false,
            hideUntrackedQuestsMapIcons = false,
            showRepeatableQuests = true,
            showEventQuests = true,
            showDungeonQuests = true,
            showRaidQuests = true,
            showPvPQuests = true,
            showAQWarEffortQuests = false,
            showQuestsInNpcTooltip = true,
            trackerEnabled = true,
            ldbDisplayText = "Questie",
            enableQuestFrameIcons = true,
            soundOnQuestComplete = false,
            questCompleteSoundChoiceName = "QuestDefault",
            soundOnObjectiveComplete = false,
            objectiveCompleteSoundChoiceName = "ObjectiveDefault",
            soundOnObjectiveProgress = false,
            objectiveProgressSoundChoiceName = "ObjectiveProgress",
            iconTheme = "custom",

            -- Custom icon theme (node_cut / mono set)
            ICON_SLAY = iconPath .. "node_cut.tga",
            ICON_LOOT = iconPath .. "loot_mono.tga",
            ICON_EVENT = iconPath .. "node_cut.tga",
            ICON_OBJECT = iconPath .. "object_mono.tga",
            ICON_TALK = iconPath .. "node_cut.tga",
            ICON_AVAILABLE_GRAY = iconPath .. "available_gray.blp",

            -- Advanced / compat profile keys
            initDelay = 0.03,
            useWotlkMapData = false,
            resetDailyQuests = true,
            weeklyResetDay = 4,
            weeklyResetHour = 6,
            useQuestieLinks = false,

            minimap = {
                hide = true,
            },

            TrackerWidth = 0,
            TrackerHeight = 0,

            townsfolkConfig = {
                [164] = false,
                [171] = false,
                ["Flight Master"] = false,
                ["Meeting Stones"] = false,
                ["Mailbox"] = false,
                ["Repair"] = false,
                ["Innkeeper"] = true,
                ["Class Trainer"] = false,
                ["Banker"] = false,
                ["Spirit Healer"] = false,
                ["Battlemaster"] = false,
                ["Weapon Master"] = false,
                ["Auctioneer"] = false,
                ["Reagents"] = false,
            },

            -- Migration
            migrationVersion = 0,
            globalMigrationSteps = {},

            debugEnabled = false,
            debugEnabledPrint = false,
            debugLevel = 0,
            skipValidation = false,
        },
        char = {
            complete = {},
            hidden = {},
            hiddenDailies = {
                nhc = {},
                hc = {},
                cooking = {},
                fishing = {},
                pvp = {},
            },
            journey = {},
            isTrackerExpanded = true,
            trackerViewMode = "quests",
        },
        global = {
            -- TBC Isle of Quel'Danas
            isleOfQuelDanasPhase = 1,
            isIsleOfQuelDanasPhaseReminderDisabled = false,
            --
            lastDailyRequestResetTime = 0,
            lastDailyRequestDate = "",
            questieLocale = 'enUS',
            questieLocaleDiff = false,
        }
    }
end
